<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Barangpoinmodel extends CI_Model
{

    public $table = 'barang_poin';
    public $id = 'tid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('tid', $q);
	$this->db->or_like('barang', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('poin', $q);
	$this->db->or_like('stock', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    public function countAllBarangPoin()
    {
        $this->db->from('barang_poin');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('tid', $q);
	$this->db->or_like('barang', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('poin', $q);
	$this->db->or_like('stock', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function getAllBarangPoin($pg,$off)
    {
        $this->db->order_by('barang','asc');
        return $this->db->get('barang_poin',$pg,$off);
    }

}

/* End of file Barangpoinmodel.php */
/* Location: ./application/models/Barangpoinmodel.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-08-15 06:18:11 */
/* http://harviacode.com */