<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by username
     */
    function get_user($username)
    {
        return $this->db->get_where('user',array('username'=>$username))->row_array();
    }
    
    /*
     * Get all user
     */
    function get_all_user()
    {
        return $this->db->get('user')->result_array();
    }

    function getAllUser($pg,$off)
    {
        $this->db->order_by('username','asc');
        return $this->db->get('user',$pg,$off)->result_array();
    }

    public function countAllUser()
    {
        $this->db->from('user');
        return $this->db->count_all_results();
    }
    
    /*
     * function to add new user
     */
    function add_user($params)
    {
        return $this->db->insert('user',$params);
    }
    
    /*
     * function to update user
     */
    function update_user($username,$params)
    {
        $this->db->where('username',$username);
        $this->db->update('user',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($username)
    {
        $this->db->delete('user',array('username'=>$username));
    }
}
