<?php
/* 
 * Generated by CRUDigniter v2.3 Beta 
 * www.crudigniter.com
 */
 
class User extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        if($this->session->userdata('isLoginAdmin') != TRUE)
            redirect('adminpanel/login','refresh');
            
        $this->load->model('admin/usermodel','usm');
        $this->load->model('admin/User_model');
    } 

    /*
     * Listing of user
     */
    function index($off = 0)
    {
        $data['menu'] = 'User';
        $username = $this->session->userdata('username');
        $data['user'] = $this->usm->getUserDetail($username);
                
        $total = $this->User_model->countAllUser();                
        $this->load->library('pagination');
        $config["base_url"] = site_url('adminpanel/user/index');
        $config["total_rows"] = $total;
        $config["per_page"] = 20;
        $config["uri_segment"] = 4;
        $this->pagination->initialize($config);
        
        $data['listuser'] = $this->User_model->getAllUser($config['per_page'],$off);
        if($this->session->flashdata('info'))
            $data['info'] = $this->session->flashdata('info');
        
        $this->load->view('admin/user/index',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
                'username' => $this->input->post('username'),
				'password' => md5($this->input->post('password')),
				'email' => $this->input->post('email'),
				'tgl_daftar' => $this->input->post('tgl_daftar'),
				'nama' => $this->input->post('nama'),
				'website' => $this->input->post('website'),
				'biodata' => $this->input->post('biodata'),
				'jenis_member' => $this->input->post('jenis_member'),
				'status' => $this->input->post('status'),
				'ip' => $this->input->post('ip'),
				'avatar' => $this->input->post('avatar'),
				'newsletter' => $this->input->post('newsletter'),
				'sent' => $this->input->post('sent'),
				'poin' => $this->input->post('poin'),
            );
            
            $this->User_model->add_user($params);
            redirect('adminpanel/user/index');
        }
        else
        {
            $data['menu'] = 'User';
            $username = $this->session->userdata('username');
            $data['user'] = $this->usm->getUserDetail($username);
            $this->load->view('admin/user/add',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($username)
    {   
        // check if the user exists before trying to edit it
        $user = $this->User_model->get_user($username);
        
        if(isset($user['username']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'email' => $this->input->post('email'),
					'tgl_daftar' => $this->input->post('tgl_daftar'),
					'nama' => $this->input->post('nama'),
					'website' => $this->input->post('website'),
					'biodata' => $this->input->post('biodata'),
					'jenis_member' => $this->input->post('jenis_member'),
					'status' => $this->input->post('status'),
					'ip' => $this->input->post('ip'),
					'avatar' => $this->input->post('avatar'),
					'newsletter' => $this->input->post('newsletter'),
					'sent' => $this->input->post('sent'),
					'poin' => $this->input->post('poin'),
                );

                $this->User_model->update_user($username,$params);            
                redirect('adminpanel/user/index');
            }
            else
            {   
                $data['userd'] = $this->User_model->get_user($username);
                $data['menu'] = 'User';
                $username = $this->session->userdata('username');
                $data['user'] = $this->usm->getUserDetail($username);
                $this->load->view('admin/user/edit',$data);
            }
        }
        else
            $this->session->set_flashdata('info', 'The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($username)
    {
        $user = $this->User_model->get_user($username);

        // check if the user exists before trying to delete it
        if(isset($user['username']))
        {
            $this->User_model->delete_user($username);
            redirect('adminpanel/user/index');
        }
        else

            $this->session->set_flashdata('info','The user you are trying to delete does not exist.');
    }
    
}
